services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Vue frontend on port 8080
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000/server
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/server:/var/www/html/server
      - ./backend/php.ini:/usr/local/etc/php/conf.d/xdebug.ini # Load custom php.ini
    ports:
      - "8000:80" # Apache Server

    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/server/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  app-network:
    driver: bridge
